# --- Fonty ---
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --- Okno ---
# Alacritty 'decorations = "none"'
hide_window_decorations false
# Alacritty 'startup_mode = "Maximized"'
initial_window_width  100c
initial_window_height 40c
# Alacritty 'padding'
window_padding_width 10
background_opacity 0.9

# --- Scrollování ---
scrollback_lines 10000
touch_scroll_multiplier 3.0

# --- Fix pro tmux ---
map ctrl+9 send_text all \x1b[57;5u
map ctrl+0 send_text all \x1b[48;5u

# --- Obecné ---
# Alacritty 'live_config_reload' (v Kitty je zapnuto automaticky)
allow_remote_control yes
listen_on unix:/tmp/mykitty
copy_on_select yes
clipboard_control write-clipboard write-primary
enable_audio_bell no

# --- Barvy (Solarized Light) ---
# Protože jsi importoval solarized_light.toml, tady je jeho Kitty verze:
# background            #fdf6e3
# foreground            #657b83
# cursor                #586e75
# selection_background  #eee8d5
# color0                #073642
# color8                #002b36
# color1                #dc322f
# color9                #cb4b16
# color2                #859900
# color10               #586e75
# color3                #b58900
# color11               #657b83
# color4                #268bd2
# color12               #839496
# color5                #d33682
# color13               #6c71c4
# color6                #2aa198
# color14               #93a1a1
# color7                #eee8d5
# color15               #fdf6e3


# BEGIN_KITTY_THEME
# Solarized Dark
include current-theme.conf
# END_KITTY_THEME
#
confirm_os_window_close 0
